x-common-config:
  &common-config
  network_mode: host
  ipc: host 
  pid: host # ?
  restart: unless-stopped

x-dds-envs:
  &dds-envs
  env_file: .env.dds

services:

  foxglove:
    image: husarion/foxglove:1.84.0
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./params/ROSbotXL.json:/foxglove/default-layout.json
    depends_on:
      rplidar: { condition: service_healthy }
      rosbot: { condition: service_healthy }
    environment:
      - DS_TYPE=foxglove-websocket
      - DS_PORT=8765
      - UI_PORT=8080
      - DISABLE_CACHE=true
      - DISABLE_INTERACTION=false

  reverse-proxy:
    image: caddy:2.6.2-alpine
    restart: unless-stopped
    network_mode: host
    depends_on:
      rosbot: { condition: service_healthy }
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

  foxglove-ds:
    image: husarion/foxglove-bridge:humble-0.7.4-20240320
    <<:
      - *common-config
      - *dds-envs
    depends_on:
      rosbot: { condition: service_healthy }
    command: ros2 launch foxglove_bridge foxglove_bridge_launch.xml port:=8766 address:=127.0.0.1 capabilities:=[clientPublish,connectionGraph,assets]

  teleop_twist_joy:
    image: husarion/teleop-twist-joy:humble-2.4.5-20240318
    depends_on:
      rosbot: { condition: service_healthy }
    <<:
      - *common-config
      - *dds-envs
    command: ros2 run teleop_twist_joy teleop_node --ros-args --params-file /teleop_twist_joy_f710_params.yaml

  rosbot:
    image: husarion/rosbot-xl:humble-0.10.0-20240216
    <<:
      - *common-config
      - *dds-envs
    command: >
      ros2 launch /husarion_utils/rosbot.launch.py
        mecanum:=${MECANUM:-True}
        include_camera_mount:=True
        healthcheck:=True

  luxonis:
    image: husarion/depthai:humble-2.8.1-20240127
    <<:
      - *common-config
      - *dds-envs
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ./params/oak-1-low-bandwidth.yaml:/params.yaml
    device_cgroup_rules:
      - 'c 189:* rmw'
    depends_on:
      rosbot: { condition: service_healthy }
    command: >
      ros2 launch depthai_ros_driver camera.launch.py
        params_file:=/params.yaml
        parent_frame:=camera_mount_link

  rplidar:
    image: husarion/rplidar:humble-1.0.1-20240216
    <<:
      - *common-config
      - *dds-envs
    devices:
      - /dev/ttyRPLIDAR:/dev/ttyUSB0
    depends_on:
      rosbot: { condition: service_healthy }
    command: >
      ros2 launch /husarion_utils/rplidar.launch.py
        serial_baudrate:=${LIDAR_BAUDRATE:-256000}
        serial_port:=/dev/ttyUSB0
        healthcheck:=True
