x-common-config:
  &common-config
  network_mode: host
  ipc: host
  restart: unless-stopped

x-dds-envs:
  &dds-envs
  env_file: .env.dds

services:

  ros2router:
    image: husarnet/ros2router:1.9.0
    <<: *common-config
    volumes:
      - ./filter.yaml:/filter.yaml
    environment:
      - USER
      - PARTICIPANTS=husarnet,shm
      - VIDEO_CODEC

  rosbot:
    image: husarion/rosbot-xl:humble-0.10.0-20240216
    <<:
      - *common-config
      - *dds-envs
    # devices:
    #   - /dev/ttyUSBDB # just for firmware flashing
    #   - /dev/bus/usb/ # just for firmware flashing
    command: >
      ros2 launch /husarion_utils/rosbot.launch.py
        mecanum:=${MECANUM:-True}

  luxonis:
    image: husarion/depthai:humble-2.8.1-20240127
    <<:
      - *common-config
      - *dds-envs
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ./params/oak-1.yaml:/camera.params.yaml
    device_cgroup_rules:
      - 'c 189:* rmw'
    # command: tail -f /dev/null
    command: >
      ros2 launch depthai_ros_driver camera.launch.py 
        params_file:=/camera.params.yaml
    # command: >
    #   ros2 launch depthai_ros_driver camera.launch.py 
    #     parent_frame:=oak-1-base-frame
    #     params_file:=/camera.params.yaml
           