services:

  image_decompressor:
    image: husarion/image-transport:humble
    restart: unless-stopped
    command: >
      ros2 run image_transport republish theora raw
      --ros-args
      --remap in/theora:=/oak/rgb/image_raw/theora
      --remap out:=/camera/my_image_raw

  # if you have NVDIA GPU and NVIDIA Container Toolkit, you can replace
  # "cpu-config" with "gpu-config"
  interface:
    image: husarion/image-tools:humble
    restart: unless-stopped
    environment:
      - DISPLAY=${DISPLAY:?err}
      - LIBGL_ALWAYS_SOFTWARE=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: ros2 run image_tools showimage --ros-args -p reliability:=best_effort --remap image:=/camera/my_image_raw

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/24

