x-common-config:
  &common-config
  network_mode: host
  ipc: host
  restart: unless-stopped

x-dds-envs:
  &dds-envs
  env_file: .env.dds

services:

  ros2router:
    image: husarnet/ros2router:1.9.0
    <<: *common-config
    environment:
      - USER
      - PARTICIPANTS=husarnet,shm

  rviz:
    image: husarion/rviz2:humble-11.2.9-20240111
    runtime: ${DOCKER_RUNTIME:-runc}
    <<:
      - *common-config
      - *dds-envs
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./params/default.rviz:/default.rviz
      - ./rviz.launch.py:/rviz.launch.py
    environment:
      - DISPLAY=${DISPLAY:?err}
      - LIBGL_ALWAYS_SOFTWARE=${LIBGL_ALWAYS_SOFTWARE:-1}
      - NVIDIA_VISIBLE_DEVICES=all # if LIBGL_ALWAYS_SOFTWARE=1 this env var is ignored
      - NVIDIA_DRIVER_CAPABILITIES=all # if LIBGL_ALWAYS_SOFTWARE=1 this env var is ignored
    command: ros2 launch /rviz.launch.py

  # joy2twist:
  #   image: husarion/joy2twist:humble-1.0.0-20240105
  #   <<:
  #     - *common-config
  #     - *dds-envs
  #   devices:
  #     - /dev/input
  #   volumes:
  #     - ./params/joy2twist.yaml:/params.yaml
  #   command: >
  #     ros2 launch joy2twist gamepad_controller.launch.py
  #       joy2twist_params_file:=/params.yaml
  #       namespace:=${ROBOT_NAMESPACE}
